### ISSUE TITLE
Question about docker

### ISSUE THREAD

**Issue by degageyisui** [BUPT-GAMMA/GraphTeam#1]
Hi,

Thank you for your great work.

I pull the image and create the container, but the container is not running after executing "docker start test". I fail to run the container successfully and it stops immediately after I start it.

**Comment by lixin4sky** [comment]
Thank you for your feedback, we will contact with you next week.

**Comment by lixin4sky** [comment]
Hi,

We have addressed this bug. You can see the latest tutorial in our readme.md. 

Thank you for your feedback!

If you have further questions, we are happy to help you.

**Comment by degageyisui** [comment]
Thanks for your reply! I successfully run the container now.
